name: Shortlinks
description: A simple, easily manageable, shortlinks solution using Jekyll and GitHub Pages
repository: frc2204/shortlinks

collections:
  shortlinks:
    output: true

defaults:
  - scope:
      path: ""
      type: "shortlinks"
    values:
      layout: "redirect"
